### ISSUE TITLE
token name in unicode (specific combinations) breaks the parser

### ISSUE THREAD

**Issue by srix** [neogeny/TatSu#140]
Tatsu (TatSu==4.4.0) grammar parsing works for unicode token names of certain combination. following python code works. But fails if "எண" is replaced by "எண்" .(எண் in Tamil language, spoken in southern part of India, means number)

the difference is "எண" is two unicode character "எ" , "ண" , while எண் is three characters "எ", "ண", " ்"

```
# -*- coding: utf-8 -*-
from __future__ import generator_stop

from codecs import open
from pprint import pprint
import tatsu
from tatsu.ast import AST

class CalcSemantics(object):
    def எண(self, ast):
        return int(ast)

    def addition(self, ast):
        return ast.left + ast.right

    def subtraction(self, ast):
        return ast.left - ast.right


def parse_factored():
    # grammar = open('calc.grammar').read()

    grammar = '''@@grammar::CALC


start
    =
    expression $
    ;


expression
    =
    | addition
    | subtraction
    | term
    ;


addition
    =
    left:expression op:'+' ~ right:term
    ;

subtraction
    =
    left:expression op:'-' ~ right:term
    ;


term
    =
    factor
    ;

factor
    =
    | '(' ~ @:expression ')'
    | எண
    ;


எண
    =
    /\d+/
    ;
'''

    parser = tatsu.compile(grammar)
    ast = parser.parse(
        '3 + 5 + ( 10 - 20 )',
        semantics=CalcSemantics()
    )

    print()
    print('# FACTORED SEMANTICS RESULT')
    pprint(ast, width=20, indent=4)
    print()


def main():
    parse_factored()

if __name__ == '__main__':
    main()
```

error message when "எண" is replaced by "எண்" .
```
srix:~/workspace/project1$ cd /home/srix/workspace/project1 ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /home/srix/workspace/project1/.venv/bin/python3.7 /home/srix/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/ptvsd_launcher.py --default --nodebug --client --host localhost --port 41791 /home/srix/workspace/project1/calc.py 
Traceback (most recent call last):
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 694, in _option
    yield
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/bootstrap.py", line 110, in block6
    self._rule_()
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 56, in wrapper
    return self._call(ruleinfo)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 519, in _call
    result = self._recursive_call(ruleinfo)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 548, in _recursive_call
    return self._invoke_rule(ruleinfo, self.memokey)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 595, in _invoke_rule
    ruleinfo.impl(self)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/bootstrap.py", line 324, in _rule_
    self._token(';')
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 632, in _token
    self._error(token, exclass=FailedToken)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 453, in _error
    raise self._make_exception(item, exclass=exclass)
tatsu.exceptions.FailedToken: (37:9) expecting ';' :
    | எண்
        ^
rule
grammar
start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 218, in parse
    result = rule()
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 56, in wrapper
    return self._call(ruleinfo)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 519, in _call
    result = self._recursive_call(ruleinfo)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 548, in _recursive_call
    return self._invoke_rule(ruleinfo, self.memokey)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 595, in _invoke_rule
    ruleinfo.impl(self)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/bootstrap.py", line 87, in _start_
    self._grammar_()
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 56, in wrapper
    return self._call(ruleinfo)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 519, in _call
    result = self._recursive_call(ruleinfo)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 548, in _recursive_call
    return self._invoke_rule(ruleinfo, self.memokey)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 595, in _invoke_rule
    ruleinfo.impl(self)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/bootstrap.py", line 116, in _grammar_
    self._closure(block6)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 791, in _closure
    self._repeat(block, prefix=sep, dropprefix=omitsep)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 778, in _repeat
    self._isolate(block)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 757, in _isolate
    block()
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/bootstrap.py", line 111, in block6
    self.add_last_node_to_name('rules')
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 700, in _option
    raise FailedCut(e)
tatsu.exceptions.FailedCut: (37:9) expecting ';' :
    | எண்
        ^
rule
grammar
start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/srix/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/srix/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/__main__.py", line 434, in main
    run()
  File "/home/srix/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/srix/workspace/project1/calc.py", line 85, in <module>
    main()
  File "/home/srix/workspace/project1/calc.py", line 82, in main
    parse_factored()
  File "/home/srix/workspace/project1/calc.py", line 69, in parse_factored
    parser = tatsu.compile(grammar)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/tool.py", line 164, in compile
    model = cache[grammar] = gen.parse(grammar, **kwargs)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 223, in parse
    raise self._furthest_exception
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 694, in _option
    yield
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/bootstrap.py", line 448, in _named_
    self._named_list_()
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 56, in wrapper
    return self._call(ruleinfo)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 519, in _call
    result = self._recursive_call(ruleinfo)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 548, in _recursive_call
    return self._invoke_rule(ruleinfo, self.memokey)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 595, in _invoke_rule
    ruleinfo.impl(self)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/bootstrap.py", line 457, in _named_list_
    self._token('+:')
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 632, in _token
    self._error(token, exclass=FailedToken)
  File "/home/srix/workspace/project1/.venv/lib/python3.7/site-packages/tatsu/contexts.py", line 453, in _error
    raise self._make_exception(item, exclass=exclass)
tatsu.exceptions.FailedToken: (37:9) expecting '+:' :
    | எண்
        ^
named_list
named
element
sequence
choice
expre
rule
grammar
start
```

**Comment by srix** [comment]
The above error happens when using the python's default `re` module. However when the regex module is installed in the above code works without error. Tatsu picks up the `regex` module automatically. By installing  `regex` module from pypi this bug can be fixed.

Since the fix is trivial, I am closing this bug.
