### ISSUE TITLE
yaml.representer.RepresenterError exception when using ast_dumps

### ISSUE THREAD

**Issue by pallavg** [neogeny/TatSu#144]
I am using python v3.7.5, and running into an error when trying to write a model AST to a YAML file.  The JSON is output OK. so I am not sure why dumping to YAML results in an error. I am not sure if this is a usage issue or some bug.

The relevant sample code/output.

```
from tatsu.yaml import ast_dump, ast_load
from tatsu.ast import asjson
from tatsu.objectmodel import Node
from tatsu.semantics import ModelBuilderSemantics

grammar = open('STIL1999.ebnf.working').read()
parser = tatsu.compile(grammar, semantics=ModelBuilderSemantics(), asmodel=True)
ast = parser.parse(open(sys.argv[1]).read())
   
print(json.dumps(asjson(ast), indent=2))
ast_dump(ast)
```

```

Parse start 2019-11-21 16:25:26.229366
Parse finish 2019-11-21 16:25:26.234759
Total = 0.005355
[
  {
    "__class__": "version",
    "ver": 1.0
  },
  {
    "__class__": "headers",
    "objs": [
      {
        "k": "Title",
        "v": "foo.gz"
      },
      {
        "k": "Date",
        "v": "Mon Nov  4 02:48:48 2019"
      },
      {
        "k": "Source",
        "v": "foo.gz"
      },
      {
        "k": "History",
        "objs": [
          {
            "__class__": "annotation",
            "ann": " This is a test "
          }
        ]
      }
    ]
  },
  [
    {
      "__class__": "signals",
      "objs": []
    }
  ]
]
Write obj model to yaml file
Traceback (most recent call last):
  File "./run.py", line 74, in <module>
    sys.exit(main())
  File "./run.py", line 60, in main
    ast_dump(ast)
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/site-packages/tatsu/yaml.py", line 50, in ast_dump
    return dump(data, object_pairs_hook=AST, **kwargs)
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/site-packages/tatsu/yaml.py", line 33, in dump
    **kwds
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/site-packages/yaml/__init__.py", line 290, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/site-packages/yaml/__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/site-packages/yaml/representer.py", line 199, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/site-packages/yaml/representer.py", line 92, in represent_sequence
    node_item = self.represent_data(item)
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/site-packages/yaml/representer.py", line 58, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/site-packages/yaml/representer.py", line 231, in represent_undefined
    raise RepresenterError("cannot represent an object", data)
yaml.representer.RepresenterError: ('cannot represent an object', <tatsu.synth.version object at 0x7ffff66bcb10>)
```

**Comment by pallavg** [comment]
Just to add, I installed the package from conda-forge and it is using version 4.4.0.

**Comment by pallavg** [comment]
So I was not successful in finding a fix for getting YAML to dump correctly.

So, I switched to trying pickle. Even then I get an error saying 'Unable to pickle weakref objects'. After a little bit of debugging, I found the following lines in objectmodel.py. I removed the weakref() and made the object just be regular references.

```
 def _adopt_children(self, node, parent=None):
        if parent is None:
            parent = self
        if isinstance(node, Node):
            node._parent = parent
            #node._parent = weakref.ref(parent)    <-- Changed this
            for c in node.children():
                node._adopt_children(c, parent=node)
        elif isinstance(node, Mapping):
            for c in node.values():
                self._adopt_children(c, parent=parent)
        elif isinstance(node, list):
            for c in node:
                self._adopt_children(c, parent=parent)

    def __setstate__(self, state):
        self.__dict__.update(state)
        if self._parent is not None:
            self._parent = self._parent
            #self._parent = weakref.ref(self._parent)  <-- Changed this
```

With this, pickling/unpickling works OK:

```
   import pickle
    obj = pickle.dumps(ast)
    new_ast = pickle.loads(obj)
    print(type(ast))
    print(type(new_ast))
    print()
    print(asjsons(ast))
    print()
    print(asjsons(new_ast))
```

Output:
```
$ ./run.py header.stil
Total parse time: 0.004204
<class 'tatsu.synth.StilSession'>
<class 'tatsu.synth.StilSession'>

{
  "__class__": "StilSession",
  "blocks": [],
  "header": {
    "__class__": "Header",
    "objs": [
      {
        "k": "Title",
        "v": "foo"
      }
    ]
  },
  "version": {
    "__class__": "Stil",
    "ver": 1.0
  }
}

{
  "__class__": "StilSession",
  "blocks": [],
  "header": {
    "__class__": "Header",
    "objs": [
      {
        "k": "Title",
        "v": "foo"
      }
    ]
  },
  "version": {
    "__class__": "Stil",
    "ver": 1.0
  }
}
```

However, I do not know if the changes I made to objectmodel.py are safe/good ones and what implications that would have on memory consumption of parsing large files, etc. Any comments?

**Comment by apalala** [comment]
The Python garbage collector should resolve the cycle implied by `_parent`, so I see no need for the `weakref`.

Could you turn the change into a pull request?

**Comment by pallavg** [comment]
Very good. I'll submit the PR in a couple of days (Thanksgiving).

**Comment by pallavg** [comment]
Hi Juancarlos - I have made the fix and submitted a PR. Please check. If acceptable, can you please release a new version so I can install the update using Anaconda? Thanks.
