### ISSUE TITLE
Comment handling interferes with simple grammars

### ISSUE THREAD

**Issue by matsjoyce** [neogeny/TatSu#59]
Using TatSu version 208e7e84e76443db46330ef4d83fd31da291fb78:

```python
>>> import tatsu
>>> g=tatsu.compile("start = '#' $;")
>>> g.parse("#", trace=True)
↙start ~1:1
#
≢'#' 
≢start ~1:1
#
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "deps/modules/tatsu/grammars.py", line 945, in parse
    **kwargs
  File "deps/modules/tatsu/contexts.py", line 211, in parse
    raise self._furthest_exception
  File "deps/modules/tatsu/contexts.py", line 203, in parse
    result = rule()
  File "deps/modules/tatsu/grammars.py", line 693, in parse
    result = self._parse_rhs(ctx, self.exp)
  File "deps/modules/tatsu/grammars.py", line 700, in _parse_rhs
    result = ctx._call(ruleinfo)
  File "deps/modules/tatsu/contexts.py", line 509, in _call
    result = self._recursive_call(ruleinfo)
  File "deps/modules/tatsu/contexts.py", line 540, in _recursive_call
    result = self._invoke_rule(ruleinfo, key)
  File "deps/modules/tatsu/contexts.py", line 573, in _invoke_rule
    ruleinfo.impl(self)
  File "deps/modules/tatsu/grammars.py", line 348, in parse
    ctx.last_node = [s.parse(ctx) for s in self.sequence]
  File "deps/modules/tatsu/grammars.py", line 348, in <listcomp>
    ctx.last_node = [s.parse(ctx) for s in self.sequence]
  File "deps/modules/tatsu/grammars.py", line 266, in parse
    return ctx._token(self.token)
  File "deps/modules/tatsu/contexts.py", line 610, in _token
    self._error(token, exclass=FailedToken)
  File "deps/modules/tatsu/contexts.py", line 435, in _error
    raise self._make_exception(item, exclass=exclass)
tatsu.exceptions.FailedToken: (1:1) expecting '#' :

^
start
```

This can be overridden by setting the `comments_re` and `eol_comments_re` to be `/$/`, but the default should really be `None`.

**Comment by apalala** [comment]
Nice catch @matsjoyce ! Would you contribute the patch/pull request?
