### ISSUE TITLE
Error message doesn't contains line on witch error happens

### ISSUE THREAD

**Issue by kwargs** [neogeny/TatSu#79]
```python
import tatsu

GRAMMAR_TEXT = """
start = ATTRIBUTE operator value ;

ATTRIBUTE = /[A-Za-z]+/;

operator = '='
         | '!='
         ;

value = NUMBER ;

NUMBER = /[0-9]+/ ;
"""


def parse(data):
    with open('gr.py', 'w') as fd:
        fd.write(tatsu.to_python_sourcecode(GRAMMAR_TEXT))
    grammar = tatsu.compile(GRAMMAR_TEXT)
    return grammar.parse(data)


for sample in ['foo = 1', 'foo']:
    print(sample)
    print(parse(sample))

```

```
python t.py
foo = 1
['foo', '=', '1']
foo
Traceback (most recent call last):
  File "t.py", line 27, in <module>
    print(parse(sample))
  File "t.py", line 22, in parse
    return grammar.parse(data)
  File "/Users/wizard/Code/TatSu/tatsu/grammars.py", line 946, in parse
    **kwargs
  File "/Users/wizard/Code/TatSu/tatsu/contexts.py", line 211, in parse
    raise self._furthest_exception
  File "/Users/wizard/Code/TatSu/tatsu/contexts.py", line 203, in parse
    result = rule()
  File "/Users/wizard/Code/TatSu/tatsu/grammars.py", line 694, in parse
    result = self._parse_rhs(ctx, self.exp)
  File "/Users/wizard/Code/TatSu/tatsu/grammars.py", line 701, in _parse_rhs
    result = ctx._call(ruleinfo)
  File "/Users/wizard/Code/TatSu/tatsu/contexts.py", line 509, in _call
    result = self._recursive_call(ruleinfo)
  File "/Users/wizard/Code/TatSu/tatsu/contexts.py", line 540, in _recursive_call
    result = self._invoke_rule(ruleinfo, key)
  File "/Users/wizard/Code/TatSu/tatsu/contexts.py", line 573, in _invoke_rule
    ruleinfo.impl(self)
  File "/Users/wizard/Code/TatSu/tatsu/grammars.py", line 349, in parse
    ctx.last_node = [s.parse(ctx) for s in self.sequence]
  File "/Users/wizard/Code/TatSu/tatsu/grammars.py", line 349, in <listcomp>
    ctx.last_node = [s.parse(ctx) for s in self.sequence]
  File "/Users/wizard/Code/TatSu/tatsu/grammars.py", line 650, in parse
    return rule()
  File "/Users/wizard/Code/TatSu/tatsu/grammars.py", line 694, in parse
    result = self._parse_rhs(ctx, self.exp)
  File "/Users/wizard/Code/TatSu/tatsu/grammars.py", line 701, in _parse_rhs
    result = ctx._call(ruleinfo)
  File "/Users/wizard/Code/TatSu/tatsu/contexts.py", line 509, in _call
    result = self._recursive_call(ruleinfo)
  File "/Users/wizard/Code/TatSu/tatsu/contexts.py", line 540, in _recursive_call
    result = self._invoke_rule(ruleinfo, key)
  File "/Users/wizard/Code/TatSu/tatsu/contexts.py", line 573, in _invoke_rule
    ruleinfo.impl(self)
  File "/Users/wizard/Code/TatSu/tatsu/grammars.py", line 401, in parse
    ctx._error('no available options')
  File "/Users/wizard/Code/TatSu/tatsu/contexts.py", line 435, in _error
    raise self._make_exception(item, exclass=exclass)
tatsu.exceptions.FailedParse: (1:1) no available options :

^
operator
start
```

Expected something like
```
  File "/Users/wizard/Code/TatSu/tatsu/contexts.py", line 435, in _error
    raise self._make_exception(item, exclass=exclass)
tatsu.exceptions.FailedParse: (1:1) no available options :
foo
^
operator
start
```

**Comment by Victorious3** [comment]
Tatsu doesn't recall the line numbers of the rules inside the grammar, but you can run `parse` with `trace=True` to get an idea of what was happening. To get better error messages you can use SkipTo (`->`) with recovery rules, semantics and Cut (`~`), see the [documentation](https://tatsu.readthedocs.io/en/stable/syntax.html).

**Comment by kwargs** [comment]
I debug it a little bit.
As I found, the 'problem' in `FailedParse` https://github.com/neogeny/TatSu/blob/3190bbf1b829a9f85a76433381925f8b2417710c/tatsu/exceptions.py#L50-L66

It use `self.pos`,  but not `self.buf.pos`.
And `buffer.pos` is changing after exception instantiation.

https://gist.github.com/kwargs/d25a6c2070e0e5b3b64d3927cf3b5791


This hack
```diff

     def __str__(self):
-        info = self.buf.line_info(self.pos)
+        info = self.buf.line_info(self.buf.pos)
         template = "{}({}:{}) {} :\n{}\n{}^\n{}"
         text = info.text.rstrip()```
```
helps - https://gist.github.com/kwargs/d25a6c2070e0e5b3b64d3927cf3b5791#file-with-failedparse-str-hack


but I maybe it break something else ;-(

**Comment by Victorious3** [comment]
Like you said, the position of the buffer could change. The output of the exception should **not** change if the buffer is mutated. 
Rather, you should make sure that the position it is initialized with is correct, and that `line_info` returns the correct results.

**Comment by Victorious3** [comment]
Something is up here. I get this as line info from running your example:
`_LineInfo(filename=u'', line=0, col=0, start=3, end=3, text=u'')`.
I think the expected output should be:
`_LineInfo(filename=u'', line=0, col=3, start=0, end=3, text=u'foo')`
The position is `3` which seems to be correct.

When I use `foo +` as input I get
`_LineInfo(filename=u'', line=0, col=4, start=0, end=5, text=u'foo +')`
which makes me think that the buffer doesn't track it correctly in some cases.

This will take a while to fix as I have to find out what it is even meant to track in the first place.

**Comment by apalala** [comment]
The issue here is that TatSu doesn't try to show the sequence preceding the error. With `trace` enabled, it is obvious that `'foo'` got parsed, and that the parse failed because there isn't any more input:

```python
import tatsu

GRAMMAR_TEXT = """
start = ATTRIBUTE operator value ;

ATTRIBUTE = /[A-Za-z]+/;

operator = '='
         | '!='
         ;

value = NUMBER ;

NUMBER = /[0-9]+/ ;
"""


def parse(data, trace=True):
    with open('gr.py', 'w') as fd:
        fd.write(tatsu.to_python_sourcecode(GRAMMAR_TEXT))
    grammar = tatsu.compile(GRAMMAR_TEXT)
    return grammar.parse(data, trace=trace)

try:
    for sample in ['foo = 1', 'foo']:
        print(sample)
        print(parse(sample))
except Exception as e:
    print(e)
```

Results in:
```
[u'foo', u'=', u'1']
foo
↙start ~1:1
foo
↙ATTRIBUTE↙start ~1:1
foo
≡'foo' /[A-Za-z]+/
≡ATTRIBUTE↙start 
↙operator↙start 
≢'=' 
≢'!=' 
≢operator↙start 
≢start ~1:1
foo
(1:1) no available options :

^
operator
start
```
