### ISSUE TITLE
Gather works with string literals/regexps but not with names

### ISSUE THREAD

**Issue by supriyo-biswas** [neogeny/TatSu#82]
I have the following grammar (whitespaces are disabled with `whitespace=''` on the `parser.parse()` method, and this compiles fine when using `tatsu.compile()`

```
start = /\s+/.{ /\S+/ }* $;
```

However, when trying to use this grammar instead:

```
ws     = /\s+/;
start  = ws.{ /\S+/ }* $;
```

I get the error mentioned below. Shouldn't both of these should be valid and accepted by Tatsu?

```
Traceback (most recent call last):
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 672, in _option
    yield
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 756, in _repeat
    self._isolate(block)
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 735, in _isolate
    block()
  File "/me/venv/lib/python3.7/site-packages/tatsu/bootstrap.py", line 99, in block5
    self._rule_()
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 54, in wrapper
    return self._call(ruleinfo)
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 509, in _call
    result = self._recursive_call(ruleinfo)
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 540, in _recursive_call
    result = self._invoke_rule(ruleinfo, key)
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 573, in _invoke_rule
    ruleinfo.impl(self)
  File "/me/venv/lib/python3.7/site-packages/tatsu/bootstrap.py", line 286, in _rule_
    self._token(';')
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 610, in _token
    self._error(token, exclass=FailedToken)
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 435, in _error
    raise self._make_exception(item, exclass=exclass)
tatsu.exceptions.FailedToken: (2:12) expecting ';' :
start  = ws.{ /\S+/ }* $;
           ^
rule
grammar
start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 203, in parse
    result = rule()
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 54, in wrapper
    return self._call(ruleinfo)
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 509, in _call
    result = self._recursive_call(ruleinfo)
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 540, in _recursive_call
    result = self._invoke_rule(ruleinfo, key)
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 573, in _invoke_rule
    ruleinfo.impl(self)
  File "/me/venv/lib/python3.7/site-packages/tatsu/bootstrap.py", line 84, in _start_
    self._grammar_()
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 54, in wrapper
    return self._call(ruleinfo)
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 509, in _call
    result = self._recursive_call(ruleinfo)
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 540, in _recursive_call
    result = self._invoke_rule(ruleinfo, key)
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 573, in _invoke_rule
    ruleinfo.impl(self)
  File "/me/venv/lib/python3.7/site-packages/tatsu/bootstrap.py", line 100, in _grammar_
    self._positive_closure(block5)
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 782, in _positive_closure
    self._repeat(block, prefix=sep, dropprefix=omitsep)
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 759, in _repeat
    self._error('empty closure')
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 678, in _option
    raise FailedCut(e)
tatsu.exceptions.FailedCut: (2:12) expecting ';' :
start  = ws.{ /\S+/ }* $;
           ^
rule
grammar
start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/me/venv/lib/python3.7/site-packages/tatsu/tool.py", line 145, in compile
    model = cache[grammar] = gen.parse(grammar, **kwargs)
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 208, in parse
    raise self._furthest_exception
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 672, in _option
    yield
  File "/me/venv/lib/python3.7/site-packages/tatsu/bootstrap.py", line 408, in _named_
    self._named_list_()
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 54, in wrapper
    return self._call(ruleinfo)
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 509, in _call
    result = self._recursive_call(ruleinfo)
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 540, in _recursive_call
    result = self._invoke_rule(ruleinfo, key)
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 573, in _invoke_rule
    ruleinfo.impl(self)
  File "/me/venv/lib/python3.7/site-packages/tatsu/bootstrap.py", line 417, in _named_list_
    self._token('+:')
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 610, in _token
    self._error(token, exclass=FailedToken)
  File "/me/venv/lib/python3.7/site-packages/tatsu/contexts.py", line 435, in _error
    raise self._make_exception(item, exclass=exclass)
tatsu.exceptions.FailedToken: (2:12) expecting '+:' :
start  = ws.{ /\S+/ }* $;
           ^
named_list
named
element
sequence
choice
expre
rule
grammar
start
```

**Comment by Victorious3** [comment]
Try to use braces, like so: `(ws).{ /\S+/ }`

The syntax is a bit brittle here (for instance, you can't put spaces around the dot) but this should work.

**Comment by supriyo-biswas** [comment]
Thanks 😄
